exclude: |
  (?x)(
    ^alembic/|
    ^app/main.py
  )
repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.1.1
  hooks:
    - id: seed-isort-config
      language_version: python3.8
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
      args: [-rc]
      language_version: python3.8
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.8
      args: [--line-length=100, --skip-string-normalization]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.1
  hooks:
    - id: flake8