version: '3'

volumes:
  pg_data:
  minio_data:

services:
  frontend:
    image: dcr.teletraan.io/eam/frontend:dev-latest

#   upstream to local eam service(default listen on 8000 port)
  nginx:
    image: nginx:latest
    ports:
      - 8061:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  # use local eam service instead docker eam service
  # if you want debug in container, uncomment ports and stop local debug service
  backend:
   image: dcr.teletraan.io/eam/backend:dev-latest
#   ports:
#   - 8000:8000
   depends_on:
     - postgres
     - redis
     - minio
   environment:
     INIT: "yes"
   command: /scripts/start

  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "max_connections=500"]

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=teletraan
    entrypoint: sh
    command: -c 'mkdir -p /data/eam && /usr/bin/minio server /data'
    ports:
      - "9000:9000"