version: "3"

volumes:
  pg_data:

services:
  frontend:
    image: syfun/jump:latest

  #   upstream to local eam service(default listen on 8000 port)
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  backend:
    image: syfun/interagent:latest
    depends_on:
      - postgres
    environment:
      INIT: "yes"
      WITH_JUMP: "False"
      WITH_SOCKETIO: "False"
    volumes:
      - ./media:/app/media
    command: /scripts/start

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "max_connections=500"]
