version: "3"

volumes:
  pg_data:
  redis:

services:
  frontend:
    image: dcr.teletraan.io/public/jump:latest

  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/media

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  backend:
    image: dcr.teletraan.io/public/interagent:latest
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - INIT=yes
    command: /scripts/start

  agent:
    image: dcr.teletraan.io/public/interagent:latest
    depends_on:
      - postgres
    env_file:
      - .env
    command: python agent.py
    volumes:
      - ./:/app

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interagent
    command: ["postgres", "-c", "max_connections=500"]
  mqtt:
    image: eclipse-mosquitto:1.6.10
    ports:
      - 1883:1883
