"""add_ad_default

Revision ID: 16801d960d18
Revises: b3dfcdb0f2d3
Create Date: 2020-08-04 19:54:48.541440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16801d960d18'
down_revision = 'b3dfcdb0f2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('default', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'default')
    # ### end Alembic commands ###
