version: "3"

volumes:
  pg_data:
  redis:

services:
  frontend:
    image: dcr.teletraan.io/public/jump:dev-latest
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/media

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  backend:
    image: dcr.teletraan.io/public/interagent:latest
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - INIT=yes
    command: /scripts/start

  agent:
    image: dcr.teletraan.io/public/interagent:latest
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: python agent.py
    volumes:
      - ./media:/app/media
      - ./config:/app/config

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interagent
    command: ["postgres", "-c", "max_connections=500"]
